spring.application.name=media-factory
spring.servlet.multipart.max-file-size=5000MB
spring.servlet.multipart.max-request-size=5000MB
server.tomcat.max-part-count=100
server.port=8080
media-factory.preflight.enabled=true
spring.datasource.url=jdbc:sqlite:./media-factory.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
